import { assignTenant, DEFAULT_TENANT_ID } from "@/lib/tenant"
import type { KPIItem, KPITemplate, ActualEntry, TemplateAllocation } from "@/types/kpi.types"

export const NAV_ITEMS = [
  { label: "KPI Items", href: "/kpi-items" },
  { label: "KPI Templates", href: "/kpi-templates" },
  { label: "Template Allocation", href: "/template-allocation" },
  { label: "Dashboard", href: "/actuals-vs-target" },
]

const SAMPLE_KPI_ITEMS_BASE = [
  {
    id: "kpi-1",
    definitionName: "On-time Delivery",
    kpiCode: "DEL-OTD",
    itemName: "On-time Delivery %",
    category: "delivery" as const,
    description: "Measures consignments delivered on or before promised date",
    shipmentModes: ["sea", "air", "road"] as const,
    tradeDirections: ["import", "export"] as const,
    jobType: "Freight Forwarding",
    regionScope: "Global",
    unitType: "percentage" as const,
    calculationType: "auto" as const,
    periodType: "monthly" as const,
    aggregation: "Average",
    trendDirection: "higher-better" as const,
    dataSource: "TMS",
    thresholds: {
      green: { min: 95, max: 100 },
      amber: { min: 90, max: 94.99 },
      red: { min: 0, max: 89.99 },
    },
    allowCarryForward: false,
    showInBuildScreen: true,
    enableAlerts: true,
    weightedScoring: true,
    visibleRoles: ["ops-exec", "ops-mgr", "branch-head"] as const,
    weight: 35,
    statusId: "active" as const,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "kpi-2",
    definitionName: "Gross Margin",
    kpiCode: "FIN-GM",
    itemName: "Gross Margin %",
    category: "financial" as const,
    description: "Gross margin achieved on handled shipment revenue",
    shipmentModes: ["sea", "air", "road", "rail"] as const,
    tradeDirections: ["import", "export", "cross-trade"] as const,
    jobType: "Pricing",
    regionScope: "Region",
    unitType: "percentage" as const,
    calculationType: "formula" as const,
    periodType: "monthly" as const,
    aggregation: "Weighted Avg",
    trendDirection: "higher-better" as const,
    dataSource: "ERP",
    formula: "(Revenue - Cost) / Revenue * 100",
    thresholds: {
      green: { min: 22, max: 100 },
      amber: { min: 18, max: 21.99 },
      red: { min: 0, max: 17.99 },
    },
    allowCarryForward: false,
    showInBuildScreen: true,
    enableAlerts: true,
    weightedScoring: true,
    visibleRoles: ["pricing-exec", "pricing-mgr", "senior-mgmt"] as const,
    weight: 40,
    statusId: "active" as const,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "kpi-3",
    definitionName: "Customer Complaint Closure",
    kpiCode: "CUS-CCR",
    itemName: "Complaint Closure TAT",
    category: "customer" as const,
    description: "Average days to close customer complaints",
    shipmentModes: ["multimodal", "courier"] as const,
    tradeDirections: ["import-clearance", "export-clearance"] as const,
    jobType: "Customer Service",
    regionScope: "Branch",
    unitType: "days" as const,
    calculationType: "manual" as const,
    periodType: "monthly" as const,
    aggregation: "Average",
    trendDirection: "lower-better" as const,
    dataSource: "CRM",
    thresholds: {
      green: { min: 0, max: 2 },
      amber: { min: 2.01, max: 4 },
      red: { min: 4.01, max: 30 },
    },
    allowCarryForward: true,
    showInBuildScreen: true,
    enableAlerts: false,
    weightedScoring: true,
    visibleRoles: ["ops-exec", "ops-mgr", "branch-head"] as const,
    weight: 25,
    statusId: "active" as const,
    createdAt: "2026-01-05T00:00:00.000Z",
    updatedAt: "2026-03-05T00:00:00.000Z",
  },
] as const satisfies Omit<KPIItem, "tenantId">[]

export const SAMPLE_KPI_ITEMS: KPIItem[] = assignTenant<KPIItem>([...SAMPLE_KPI_ITEMS_BASE], DEFAULT_TENANT_ID)

const SAMPLE_TEMPLATES_BASE = [
  {
    id: "tmpl-1",
    templateName: "Operations Executive Monthly",
    templateCode: "OPS-MTH-01",
    category: "Operations",
    applicableRoles: ["leadership"] as const,
    shipmentModes: ["sea", "air", "road"] as const,
    periodType: "monthly" as const,
    description: "Monthly scorecard for operations execution team.",
    statusId: "active" as const,
    kpiItems: [
      { kpiItemId: "kpi-1", kpiCode: "DEL-OTD", kpiName: "On-time Delivery %", unitType: "percentage" as const, weight: 60, displayOrder: 1 },
      { kpiItemId: "kpi-3", kpiCode: "CUS-CCR", kpiName: "Complaint Closure TAT", unitType: "days" as const, weight: 40, displayOrder: 2 },
    ],
    createdAt: "2026-01-10T00:00:00.000Z",
  },
  {
    id: "tmpl-2",
    templateName: "Pricing Manager Quarterly",
    templateCode: "PRC-QTR-01",
    category: "Finance",
    applicableRoles: ["branch-head"] as const,
    shipmentModes: ["sea", "air", "multimodal"] as const,
    periodType: "quarterly" as const,
    description: "Quarterly profitability-focused KPI template for pricing.",
    statusId: "active" as const,
    kpiItems: [{ kpiItemId: "kpi-2", kpiCode: "FIN-GM", kpiName: "Gross Margin %", unitType: "percentage" as const, weight: 100, displayOrder: 1 }],
    createdAt: "2026-01-12T00:00:00.000Z",
  },
] as const satisfies Omit<KPITemplate, "tenantId">[]

export const SAMPLE_TEMPLATES: KPITemplate[] = assignTenant<KPITemplate>([...SAMPLE_TEMPLATES_BASE], DEFAULT_TENANT_ID)

const SAMPLE_ALLOCATIONS_BASE = [
  {
    id: "alloc-1",
    templateId: "tmpl-1",
    allocatedTo: "North Ops Team",
    allocatedToType: "team" as const,
    hierarchyLevel: "sales-lead" as const,
    fiscalYear: "2026",
    periodType: "monthly" as const,
    statusId: "confirmed" as const,
    createdAt: "2026-01-15T00:00:00.000Z",
    targets: [
      { kpiItemId: "kpi-1", kpiCode: "DEL-OTD", kpiName: "On-time Delivery %", unitType: "percentage" as const, weight: 60, annualTarget: 96, h1Target: 95, h2Target: 97, q1Target: 95, q2Target: 95, q3Target: 97, q4Target: 97 },
      { kpiItemId: "kpi-3", kpiCode: "CUS-CCR", kpiName: "Complaint Closure TAT", unitType: "days" as const, weight: 40, annualTarget: 2, h1Target: 2.2, h2Target: 1.8, q1Target: 2.2, q2Target: 2.2, q3Target: 1.8, q4Target: 1.8 },
    ],
  },
] as const satisfies Omit<TemplateAllocation, "tenantId">[]

export const SAMPLE_ALLOCATIONS: TemplateAllocation[] = assignTenant<TemplateAllocation>([...SAMPLE_ALLOCATIONS_BASE], DEFAULT_TENANT_ID)

const SAMPLE_ACTUALS_BASE = [
  {
    id: "act-1",
    allocationId: "alloc-1",
    employeeId: "EMP-001",
    employeeName: "Akhil Nair",
    role: "ops-exec" as const,
    kpiItemId: "kpi-1",
    kpiName: "On-time Delivery %",
    unitType: "percentage" as const,
    target: 95,
    actual: 96.4,
    attainmentPct: 101.47,
    priorPeriodPct: 94.2,
    ragStatus: "green" as const,
    trend: [93, 94, 95, 96.4],
    period: "Q1",
    fiscalYear: "2026",
  },
  {
    id: "act-2",
    allocationId: "alloc-1",
    employeeId: "EMP-001",
    employeeName: "Akhil Nair",
    role: "ops-exec" as const,
    kpiItemId: "kpi-3",
    kpiName: "Complaint Closure TAT",
    unitType: "days" as const,
    target: 2.2,
    actual: 2.8,
    attainmentPct: 78.57,
    priorPeriodPct: 81.2,
    ragStatus: "amber" as const,
    trend: [3.4, 3, 2.9, 2.8],
    period: "Q1",
    fiscalYear: "2026",
  },
] as const satisfies Omit<ActualEntry, "tenantId">[]

export const SAMPLE_ACTUALS: ActualEntry[] = assignTenant<ActualEntry>([...SAMPLE_ACTUALS_BASE], DEFAULT_TENANT_ID)
